#! /bin/bash

if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
	xrandr --output eDP-1 --primary --mode "1920x1200" --rotate normal --output DP-2 --mode "2560x1080" --rotate normal --right-of eDP-1 
	bspc monitor DP-2 -d 1 2 3 4 5 6 7 8
	bspc monitor eDP-1 -d 9 0
else
	xrandr --output eDP-1 --primary --mode "1920x1200" --rotate normal
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config automatic_scheme alternate
bspc config border_width 2
bspc config window_gap 10
bspc config focused_border_color "#8BE9FD"

bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer = true

polybar.sh
