#! /bin/sh
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#8BE9FD"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a WhatsApp desktop=^0
#bspc rule -a Surf state=tiled

~/.local/bin/startup
