#! /bin/sh
# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"
killall -q polybar


intern=eDP1
extern=HDMI2

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --mode "1920x1200"
    bspc monitor $intern -d 1 2 3 4 5 6 7 8 9 0
    polybar internal &
    xwallpaper --zoom ~/.local/wallpapers/dark.jpg
else
    xrandr --output "$intern" --off --output "$extern" --mode "2560x1080"
    bspc monitor $extern -d 2 3 4 5 6 7 8 9 0
    polybar external &
    xwallpaper --zoom ~/.local/wallpapers/dark.jpg
fi  


bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#8BE9FD"

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# initialstate &
