#! /bin/sh
# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


intern=eDP1
extern=HDMI2

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
    bspc monitor $intern -d 1 2 3 4 5 6 7 8 9
    bspc desktop -f 0
    polybar internal &
else
    xrandr --output "$intern" --off --output "$extern" --mode "2560x1080"
    bspc monitor $extern -d 1 2 3 4 5 6 7 8 9 
    bspc desktop -f 0
    polybar external &
fi  


bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#8BE9FD"

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a WhatsApp desktop=^0
bspc rule -a Surf state=tiled

